#!/usr/bin/env python3
# Documentation image pipeline for assets.ha-paneld.com.
#
# Hardware photographs and vendor product shots are served from a Cloudflare R2 bucket rather than
# committed to this repository. The repository keeps only this tool and docs/img/manifest.txt, which
# records every published object with its SHA-256 so the served set is enumerable and verifiable.
#
#   ingest   copy a source image -> sRGB WebP with ALL metadata stripped -> hash -> manifest
#   check    verify manifest and local staging agree, in both directions
#   upload   publish staged objects to R2 (refuses to overwrite an existing key)
#   verify   fetch every published object and confirm it matches the manifest
#
# Typical use:
#   python3 tools/docs-assets/assets.py ingest photo.jpg --name nspanel-pro-front --provenance own
#   python3 tools/docs-assets/assets.py check
#   python3 tools/docs-assets/assets.py upload
#   python3 tools/docs-assets/assets.py verify
#
# Two rules this tool enforces mechanically, because both are unrecoverable if broken:
#
#   1. Published objects are PERMANENT. A URL that has appeared in a commit must keep resolving to
#      the same bytes forever, because git pins the pointer and not the resource. `upload` refuses to
#      replace an object whose content differs. Superseding an image means publishing a new key.
#   2. Everything lives under the docs/ prefix, never the bucket root. Paths cannot be reorganised
#      later, so the namespace is reserved on day one: docs/ here, brand/ left free.
#
# Metadata stripping is a hard gate, not a courtesy: camera EXIF carries GPS coordinates and body
# serial numbers, and these photographs are taken at home. Ingest fails rather than publishing an
# image it cannot prove is clean.

import argparse
import datetime
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.request

# --- layout ------------------------------------------------------------------------------------

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
MANIFEST = os.path.join(REPO, "docs", "img", "manifest.txt")

# The untouched originals and the exact published bytes are kept outside this repository, because
# anything committed here is permanent. Point HA_PANELD_DOCS_ASSETS_DIR at that store; it otherwise
# defaults to an ignored directory beside the checkout.
ASSET_STORE = os.environ.get("HA_PANELD_DOCS_ASSETS_DIR") or os.path.join(REPO, ".docs-assets")
ORIGINALS = os.path.join(ASSET_STORE, "originals")
STAGING = os.path.join(ASSET_STORE, "published")

BASE_URL = "https://assets.ha-paneld.com"
PREFIX = "docs"                      # every key starts here; the bucket root stays reserved
RCLONE_REMOTE = os.environ.get("HA_PANELD_R2_REMOTE", "ha-paneld-r2")
BUCKET = os.environ.get("HA_PANELD_R2_BUCKET", "ha-paneld-assets")

PROVENANCE = ("own", "vendor", "contributor")
COLUMNS = ("key", "sha256", "bytes", "dimensions", "provenance", "source", "captured", "licence")

MAX_WIDTH = 1600                     # generous enough for high-DPI; docs render at <= 900
QUALITY = 82


def fail(msg):
    print("error: " + msg, file=sys.stderr)
    sys.exit(1)


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


# --- manifest ----------------------------------------------------------------------------------

def read_manifest():
    if not os.path.exists(MANIFEST):
        return []
    rows = []
    with open(MANIFEST, encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) != len(COLUMNS):
                fail("%s:%d has %d fields, expected %d" % (MANIFEST, n, len(parts), len(COLUMNS)))
            rows.append(dict(zip(COLUMNS, parts)))
    return rows


def write_manifest(rows):
    os.makedirs(os.path.dirname(MANIFEST), exist_ok=True)
    rows = sorted(rows, key=lambda r: r["key"])
    with open(MANIFEST, "w", encoding="utf-8") as f:
        f.write("# Published objects on %s — one per line, tab separated.\n" % BASE_URL)
        f.write("# Generated by tools/docs-assets/assets.py; do not hand-edit.\n")
        f.write("#\n")
        f.write("# Objects are PERMANENT: an entry here may gain corrections to its metadata columns,\n")
        f.write("# but a key must never be deleted, renamed or repointed at different bytes. Historical\n")
        f.write("# commits reference these URLs and cannot be corrected.\n")
        f.write("#\n")
        f.write("# 'source' is a courtesy record of where a third-party image came from. It is expected\n")
        f.write("# to rot; the served copy is the durable artefact and nothing depends on the source.\n")
        f.write("#\n")
        f.write("# " + "\t".join(COLUMNS) + "\n")
        for r in rows:
            f.write("\t".join(r[c] for c in COLUMNS) + "\n")


# --- ingest ------------------------------------------------------------------------------------

def has_alpha(im):
    return im.mode in ("RGBA", "LA", "PA") or "transparency" in im.info


def strip_and_encode(src, dest, max_width, quality, lossless=None):
    """Re-encode to sRGB WebP with no EXIF, XMP or ICC. Returns (width, height, lossless)."""
    try:
        from PIL import Image
    except ImportError:
        fail("Pillow is required: pip install Pillow")

    with Image.open(src) as im:
        # Transparency must survive. Flattening to RGB composites a logo or line drawing onto black,
        # which destroys it silently — the file is still valid, just wrong.
        alpha = has_alpha(im)
        mode = "RGBA" if alpha else "RGB"

        # Graphics with hard edges (wordmarks, diagrams, line art, UI screenshots) ring badly under
        # lossy WebP — and compress BETTER losslessly, because flat colour regions cost almost
        # nothing while lossy spends bits inventing gradients. Measured on the 1600x1024 hero
        # screenshot: 61 KB lossless against 168 KB at q90, and the PNG it replaced was 90 KB.
        #
        # Alpha alone is too narrow a signal: a palette screenshot has no alpha and would have been
        # encoded lossy, larger AND degraded. A bounded unique-colour count catches artwork of every
        # kind while still excluding photographs, which blow past the limit immediately.
        if lossless is None:
            lossless = alpha or im.getcolors(maxcolors=4096) is not None

        icc = im.info.get("icc_profile")
        # Convert a non-sRGB source into sRGB before discarding its profile, so dropping the profile
        # does not silently shift colour. If ImageCms is unavailable the profile is still dropped —
        # stripping metadata matters more here than exact colour fidelity.
        if icc:
            try:
                import io
                from PIL import ImageCms
                src_profile = ImageCms.ImageCmsProfile(io.BytesIO(icc))
                im = ImageCms.profileToProfile(im, src_profile, ImageCms.createProfile("sRGB"),
                                               outputMode=mode)
            except Exception:
                pass

        im = im.convert(mode)
        if im.width > max_width:
            height = round(im.height * max_width / im.width)
            im = im.resize((max_width, height), Image.LANCZOS)

        size = (im.width, im.height)
        # Passing an empty value for each is defensive, not the guarantee: Pillow 10.2 was measured
        # dropping EXIF here even without it, but that is version-dependent behaviour and a silent
        # regression would leak GPS. assert_clean() below is what actually guarantees the strip, by
        # inspecting the encoded file rather than trusting the encoder.
        im.save(dest, "WEBP", quality=quality, method=6, lossless=lossless,
                exif=b"", xmp=b"", icc_profile=b"")
    return size + (lossless,)


SVG_FORBIDDEN = ("script", "foreignobject", "iframe", "use", "image")


def sanitise_svg(src, dest):
    """Copy an SVG through, refusing anything that could execute or fetch. Returns (w, h)."""
    text = open(src, encoding="utf-8").read()

    # An SVG is markup, not pixel data, so it carries no EXIF to strip — but it can carry script,
    # external references and embedded raster payloads. This is a docs badge/diagram path, so the
    # safe move is to refuse those outright rather than attempt to rewrite them.
    lowered = text.lower()
    for tag in SVG_FORBIDDEN:
        if re.search(r"<\s*%s\b" % tag, lowered):
            fail("%s contains a <%s> element; refusing to publish executable or fetching SVG" % (src, tag))
    for attr in ("onload", "onclick", "onerror", "onmouseover"):
        if attr in lowered:
            fail("%s contains an %s handler; refusing to publish executable SVG" % (src, attr))
    if re.search(r"(href|xlink:href)\s*=\s*[\"\']\s*(https?:|//)", lowered):
        fail("%s references an external URL; a published asset must be self-contained" % src)

    with open(dest, "w", encoding="utf-8") as f:
        f.write(text)

    w = re.search(r'\bwidth\s*=\s*["\']([0-9.]+)', text)
    h = re.search(r'\bheight\s*=\s*["\']([0-9.]+)', text)
    return (int(float(w.group(1))) if w else 0, int(float(h.group(1))) if h else 0)


def assert_clean(path):
    """Fail if the encoded file still carries identifying metadata."""
    from PIL import Image

    with open(path, "rb") as f:
        blob = f.read()
    if blob[:4] != b"RIFF" or blob[8:12] != b"WEBP":
        fail("%s is not a WebP file" % path)

    # Walk the RIFF chunk list rather than substring-searching, so image data cannot cause a false
    # positive and a real metadata chunk cannot hide behind one.
    offset, found = 12, []
    while offset + 8 <= len(blob):
        fourcc = blob[offset:offset + 4]
        length = int.from_bytes(blob[offset + 4:offset + 8], "little")
        if fourcc in (b"EXIF", b"XMP ", b"ICCP"):
            found.append(fourcc.decode("ascii").strip())
        offset += 8 + length + (length & 1)
    if found:
        fail("%s still contains metadata chunks: %s" % (path, ", ".join(found)))

    with Image.open(path) as im:
        if im.getexif():
            fail("%s still reports EXIF tags" % path)
        for key in ("exif", "xmp", "icc_profile"):
            if im.info.get(key):
                fail("%s still carries %s" % (path, key))


def cmd_ingest(args):
    if not os.path.exists(args.source):
        fail("no such file: %s" % args.source)
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", args.name):
        fail("--name must be lowercase kebab-case: %r" % args.name)
    if args.provenance != "own" and not args.source_url:
        fail("--source-url is required for %s imagery" % args.provenance)

    category = args.category.strip("/")
    if not re.fullmatch(r"[a-z0-9]+(?:[-/][a-z0-9]+)*", category):
        fail("--category must be lowercase kebab-case path segments: %r" % category)

    os.makedirs(ORIGINALS, exist_ok=True)
    is_svg = os.path.splitext(args.source)[1].lower() == ".svg"
    ext = "svg" if is_svg else "webp"
    tmp = os.path.join(STAGING, ".tmp-%s.%s" % (args.name, ext))
    os.makedirs(STAGING, exist_ok=True)

    if is_svg:
        width, height = sanitise_svg(args.source, tmp)
        lossless = True                      # vector: nothing is resampled
    else:
        width, height, lossless = strip_and_encode(args.source, tmp, args.max_width, args.quality,
                                                   args.lossless)
        assert_clean(tmp)

    digest = sha256_file(tmp)
    key = "%s/%s/%s-%s.%s" % (PREFIX, category, args.name, digest[:8], ext)
    dest = os.path.join(STAGING, key)

    rows = read_manifest()
    existing = {r["key"]: r for r in rows}
    if key in existing:
        if existing[key]["sha256"] == digest:
            os.remove(tmp)
            print("already published, nothing to do: %s" % key)
            return
        fail("key %s exists with different content — keys are permanent, choose a new --name" % key)

    os.makedirs(os.path.dirname(dest), exist_ok=True)
    os.replace(tmp, dest)

    # Keep the untouched source alongside the published bytes, so the CDN is never the only copy.
    original = os.path.join(ORIGINALS, "%s%s" % (args.name, os.path.splitext(args.source)[1].lower()))
    if not os.path.exists(original):
        shutil.copy2(args.source, original)

    rows.append({
        "key": key,
        "sha256": digest,
        "bytes": str(os.path.getsize(dest)),
        "dimensions": "%dx%d" % (width, height),
        "provenance": args.provenance,
        "source": args.source_url or "-",
        "captured": args.captured or datetime.date.today().isoformat(),
        "licence": args.licence or ("apache-2.0" if args.provenance == "own" else "identification-use"),
    })
    write_manifest(rows)

    print("staged   %s" % dest)
    print("original %s" % original)
    print("url      %s/%s" % (BASE_URL, key))
    print("sha256   %s  (%s)" % (digest, "lossless" if lossless else "lossy q%d" % args.quality))


# --- check / upload / verify ---------------------------------------------------------------------

def cmd_check(args):
    rows = read_manifest()
    problems = []

    for r in rows:
        if not r["key"].startswith(PREFIX + "/"):
            problems.append("%s is outside the %s/ prefix — the bucket root is reserved"
                            % (r["key"], PREFIX))
        local = os.path.join(STAGING, r["key"])
        if not os.path.exists(local):
            problems.append("%s is in the manifest but missing from staging" % r["key"])
            continue
        actual = sha256_file(local)
        if actual != r["sha256"]:
            problems.append("%s hash mismatch: manifest %s, staging %s"
                            % (r["key"], r["sha256"][:12], actual[:12]))
        if not any(r["key"].endswith("-%s.%s" % (r["sha256"][:8], e)) for e in ("webp", "svg")):
            problems.append("%s is not named after its own hash" % r["key"])

    known = {r["key"] for r in rows}
    for root, _dirs, files in os.walk(STAGING):
        for name in files:
            if name.startswith(".tmp-"):
                continue
            key = os.path.relpath(os.path.join(root, name), STAGING)
            if key not in known:
                problems.append("%s is staged but absent from the manifest" % key)

    for p in problems:
        print("FAIL " + p)
    print("%d entries, %d problems" % (len(rows), len(problems)))
    return 1 if problems else 0


def rclone_target(key):
    return "%s:%s/%s" % (RCLONE_REMOTE, BUCKET, key)


def cmd_upload(args):
    if cmd_check(args):
        fail("refusing to upload while `check` reports problems")

    # `rclone lsjson` returns non-zero both for a missing object and for a misconfigured or
    # unauthorised remote, so without this preflight an auth failure reads as "nothing published
    # yet" and every object looks like it needs uploading. Prove the remote answers first.
    if not args.dry_run:
        probe = subprocess.run(["rclone", "lsd", "%s:%s" % (RCLONE_REMOTE, BUCKET)],
                               capture_output=True, text=True)
        if probe.returncode != 0:
            fail("remote %s:%s is not reachable — check rclone config and the R2 token:\n%s"
                 % (RCLONE_REMOTE, BUCKET, probe.stderr.strip()))

    rows = read_manifest()
    published = 0
    for r in rows:
        key, local = r["key"], os.path.join(STAGING, r["key"])
        # Parse the JSON rather than comparing strings: rclone pretty-prints an empty result as
        # "[\n]", so a naive check for "[]" reads every absent object as present and silently skips
        # publishing it — the tool then reports success having uploaded nothing.
        probe = subprocess.run(["rclone", "lsjson", rclone_target(key)],
                               capture_output=True, text=True)
        present = False
        if probe.returncode == 0:
            try:
                present = bool(json.loads(probe.stdout or "[]"))
            except json.JSONDecodeError:
                fail("could not parse rclone output while probing %s:\n%s" % (key, probe.stdout))
        if present:
            print("exists   %s" % key)
            continue
        if args.dry_run:
            print("would upload %s" % key)
            continue
        # --immutable makes rclone refuse to modify an object that already exists, so the permanence
        # rule survives a race between the probe above and the copy below.
        result = subprocess.run(
            ["rclone", "copyto", "--immutable", "--header-upload",
             "Cache-Control: public, max-age=31536000, immutable", local, rclone_target(key)],
            capture_output=True, text=True)
        if result.returncode != 0:
            fail("upload failed for %s:\n%s" % (key, result.stderr.strip()))
        print("uploaded %s" % key)
        published += 1
    print("%d newly published" % published)
    return 0


def cmd_verify(args):
    rows = read_manifest()
    problems = []
    for r in rows:
        url = "%s/%s" % (BASE_URL, r["key"])
        # Cloudflare answers urllib's default "Python-urllib/x.y" User-Agent with 403, so a request
        # without this header fails in a way that looks like a broken bucket rather than a rejected
        # client. Identify the tool honestly instead of impersonating a browser.
        request = urllib.request.Request(url, headers={
            "User-Agent": "ha-paneld-docs-assets/1.0 (+https://github.com/panel-assistant/android)",
        })
        try:
            with urllib.request.urlopen(request, timeout=30) as resp:
                body = resp.read()
                headers = resp.headers
        except Exception as exc:
            problems.append("%s did not fetch: %s" % (url, exc))
            continue

        digest = hashlib.sha256(body).hexdigest()
        if digest != r["sha256"]:
            # Either the manifest is stale or a published object was substituted. Both are serious:
            # the bucket credential is the only isolation boundary in a shared Cloudflare account.
            problems.append("%s CONTENT MISMATCH: expected %s, served %s"
                            % (url, r["sha256"][:12], digest[:12]))
        expected = "image/svg+xml" if r["key"].endswith(".svg") else "image/webp"
        ctype = headers.get("Content-Type", "")
        if expected not in ctype:
            problems.append("%s served as %r, expected %s" % (url, ctype, expected))
        cache = headers.get("Cache-Control", "")
        if "immutable" not in cache:
            problems.append("%s missing immutable cache header (got %r)" % (url, cache))
        if args.verbose:
            print("ok %s  %s  %s" % (url, ctype, headers.get("CF-Cache-Status", "-")))

    for p in problems:
        print("FAIL " + p)
    print("%d entries, %d problems" % (len(rows), len(problems)))
    return 1 if problems else 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1] if __doc__ else None)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("ingest", help="convert, strip, hash and record a source image")
    p.add_argument("source")
    p.add_argument("--name", required=True, help="lowercase kebab-case, e.g. nspanel-pro-front")
    p.add_argument("--category", default="hardware", help="key path under docs/ (default: hardware)")
    p.add_argument("--provenance", required=True, choices=PROVENANCE)
    p.add_argument("--source-url", help="required for vendor/contributor imagery")
    p.add_argument("--captured", help="ISO date (default: today)")
    p.add_argument("--licence")
    p.add_argument("--max-width", type=int, default=MAX_WIDTH)
    p.add_argument("--quality", type=int, default=QUALITY)
    encoding = p.add_mutually_exclusive_group()
    encoding.add_argument("--lossless", dest="lossless", action="store_true", default=None,
                          help="force lossless (default for images carrying alpha)")
    encoding.add_argument("--lossy", dest="lossless", action="store_false",
                          help="force lossy even if the image carries alpha")
    p.set_defaults(func=cmd_ingest)

    p = sub.add_parser("check", help="verify manifest and staging agree, both directions")
    p.set_defaults(func=cmd_check)

    p = sub.add_parser("upload", help="publish staged objects to R2, never overwriting")
    p.add_argument("--dry-run", action="store_true")
    p.set_defaults(func=cmd_upload)

    p = sub.add_parser("verify", help="fetch published objects and check them against the manifest")
    p.add_argument("--verbose", action="store_true")
    p.set_defaults(func=cmd_verify)

    args = parser.parse_args()
    sys.exit(args.func(args) or 0)


if __name__ == "__main__":
    main()
